title: JonXia1337-博客
description: ""
author: 
  name: "JonXia1337"
  email: ""
  url: "https://jonxia.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
safe: false 
future: true
url: "https://jonxia.github.io"
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "JonXia1337"
year : "2019"

page: 
  summary: google sitemap xml, Open Graph and plain old "meta"-tags. 
  tags: [jekyll,blogging,facebook,metadata]
